repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0  # Use the latest stable version
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-json

-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.47.0  # Use the latest stable version
    hooks:
    -   id: markdownlint
        args: ["--config", ".markdownlint.json"]

-   repo: https://github.com/bemeurer/beautysh
    rev: 6.0.1
    hooks:
      - id: beautysh  # Format Shell scripts
